### ISSUE TITLE
Java runs out of memory after running Burp.history

### ISSUE THREAD

**Issue by nitrocode** [mwielgoszewski/jython-burp-api#10]
How to avoid the java.lang.OutOfMemoryError: Java heap space?

```
Burp.history[0]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\bhatiar\git\jython-burp-api\Lib\burp_extender.py", line 341, in <lambda>
    history = property(lambda burp: list(burp.getProxyHistory()))
  File "C:\Users\bhatiar\git\jython-burp-api\Lib\burp_extender.py", line 339, in getProxyHistory
    yield HttpRequest(request, _burp=self)
  File "C:\Users\bhatiar\git\jython-burp-api\Lib\gds\burp\models.py", line 58, in __init__
    self.response = HttpResponse(getattr(messageInfo, 'response', None),
  File "C:\Users\bhatiar\git\jython-burp-api\Lib\gds\burp\models.py", line 324, in __init__
    self.version, self.status_code, self.reason, self._headers, self.body = \
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:135)
	at java.io.DataOutputStream.writeByte(DataOutputStream.java:153)
	at org.python.core.PyArray.toStream(PyArray.java:1831)
```

**Comment by nitrocode** [comment]
I used this workaround to start Burp which allocates 4 GB of memory to Burp.

    java -Xmx4g -jar burp_suite_pro.jar

Now when I run `Burp.history`, it shows this after a very long time.

```
>>> Burp.history[0]
<HttpRequest [/]
```

I wonder why it takes so long...

**Comment by mwielgoszewski** [comment]
So, `.history` is a property which calls `list()` on  `getProxyHistory` internally, which returns a generator. Calling `list()` on a generator exhausts it, causing it to load all contents into memory. Preferred way would be to simply do:

```
>>> history = Burp.getProxyHistory()
>>> req1 = next(history)
>>> req2 = next(history)
>>> for r in history:
... r
# req3
# req4
# etc...
>>> 
```

**Comment by nitrocode** [comment]
That's a great workaround.

Thank you
