### ISSUE TITLE
Failed to create Burp project :Null PointerException

### ISSUE THREAD

**Issue by halley-eng** [mwielgoszewski/jython-burp-api#15]
Hello . 
          There is some problem with me when i start burpsuite1.7 and 1.6  via  jython

the burp show that
![image](https://cloud.githubusercontent.com/assets/5844104/20962948/71466ba0-bca6-11e6-940e-25fff475d0b8.png)
and the terminal show :

![image](https://cloud.githubusercontent.com/assets/5844104/20963023/ad9e9ba4-bca6-11e6-89c2-4b93ae0a2435.png)

is there someone can help me ?  Thanks  !

**Comment by dorneanu** [comment]
I'm having the same problem...

**Comment by j0ez1** [comment]
The same

**Comment by anilkumar-pcs** [comment]
Same for me too.

Did you guys find any other workaround for the issue?

**Comment by johndekroon** [comment]
Same problem

**Comment by jkryanchou** [comment]
Any solution on it?

**Comment by jkryanchou** [comment]
Any solution on it?

**Comment by nitintsocial** [comment]
Kindly update here if someone resolves this error or if any workaround for this error.

**Comment by jkryanchou** [comment]
I thought the new version burp would be easy to meet this issue.  Someone would work it out sooner or later.

**Comment by nielei-0906** [comment]
I moved Burp to the C drive and solved the issue.

**Comment by bwyyoung** [comment]
I solved this by running the correct versions of Jython, Burp Suite and Java:

```
export PATH="/opt/jdk1.8.0_202/bin:$PATH"
find . -name "*.class" -delete
javac -cp jython-standalone-2.7-b1.jar java/src/*.java java/src/burp/*.java
java -Xmx1g -jar jython-standalone-2.7-b1.jar -Dpython.path=Lib/ run.py -i -d -B burpsuite_pro_v1.5.11.jar

Your JRE appears to be version 1.8.0_202 from Oracle Corporation
Burp has not been fully tested on this platform and you may experience problems.
2026-01-27 02:33:15,221 - BurpExtender - DEBUG - initializing interpreter with postProperties: {}
2026-01-27 02:33:15,237 - BurpExtender - DEBUG - Initializing interpreter with preProperties: {java.runtime.name=Java(TM) SE Runtime Environment, sun.boot.library.path=/opt/jdk1.8.0_202/jre/lib/amd64, java.vm.version=25.202-b08, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, path.separator=:, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, user.country=US, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/home/kali/Documents/headless-project/jython-burp-api, jline.UnixTerminal.input.encoding=ISO-8859-1, java.runtime.version=1.8.0_202-b08, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, java.endorsed.dirs=/opt/jdk1.8.0_202/jre/lib/endorsed, os.arch=amd64, java.io.tmpdir=/tmp, line.separator=
, java.vm.specification.vendor=Oracle Corporation, os.name=Linux, sun.jnu.encoding=UTF-8, jline.WindowsTerminal.input.encoding=ISO-8859-1, python.console=org.python.util.ReadlineConsole, java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, sun.awt.enableExtraMouseButtons=true, java.specification.name=Java Platform API Specification, java.class.version=52.0, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=6.12.38+kali-amd64, networkaddress.cache.ttl=299, user.home=/home/kali, user.timezone=America/New_York, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=UTF-8, java.specification.version=1.8, sun.security.ssl.allowUnsafeRenegotiation=false, networkaddress.cache.negative.ttl=59, java.class.path=jython-standalone-2.7-b1.jar, user.name=kali, python.console.encoding=UTF-8, java.vm.specification.version=1.8, sun.java.command=jython-standalone-2.7-b1.jar -Dpython.path=Lib/ run_2.7-b1_20130210.py -i -d -B burpsuite_pro_v1.5.11.jar, java.home=/opt/jdk1.8.0_202/jre, sun.arch.data.model=64, user.language=en, java.specification.vendor=Oracle Corporation, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, java.version=1.8.0_202, java.ext.dirs=/opt/jdk1.8.0_202/jre/lib/ext:/usr/java/packages/lib/ext, sun.boot.class.path=/opt/jdk1.8.0_202/jre/lib/resources.jar:/opt/jdk1.8.0_202/jre/lib/rt.jar:/opt/jdk1.8.0_202/jre/lib/sunrsasign.jar:/opt/jdk1.8.0_202/jre/lib/jsse.jar:/opt/jdk1.8.0_202/jre/lib/jce.jar:/opt/jdk1.8.0_202/jre/lib/charsets.jar:/opt/jdk1.8.0_202/jre/lib/jfr.jar:/opt/jdk1.8.0_202/jre/classes, java.vendor=Oracle Corporation, python.cachedir.skip=true, python.path=Lib/, file.separator=/, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, sun.font.fontmanager=sun.awt.X11FontManager, sun.io.unicode.encoding=UnicodeLittle, sun.cpu.endian=little, sun.cpu.isalist=}
Jython 2.7b1 (default:ac42d59644e9, Feb 9 2013, 15:24:52) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_202
>>> 2026-01-27 02:33:15,426 - BurpExtender - INFO - Interactive interpreter ready...
2026-01-27 02:33:15,529 - BurpExtender - DEBUG - Monitoring /home/kali/Documents/headless-project/jython-burp-api/burp.ini for changes
2026-01-27 02:33:15,533 - BurpExtender - DEBUG - Monitoring /home/kali/Documents/headless-project/jython-burp-api/Lib/gds/burp/menu/console.py for changes

>>> Burp
```


Take note the last commit for run.py was Jan 5 2013, which means the last jython version tested to work with run.py is [2.5.3](https://central.sonatype.com/artifact/org.python/jython-standalone/2.5.3) (2012-08-14). I however used [2.7-b1](https://central.sonatype.com/artifact/org.python/jython-standalone/2.7-b1) (2013-02-10) and that one works.

There is also a need to use these older versions of jython because of changes in the way this line is called in run.py in the latest Jython 2.7.4. There were changes to the console class resulting in a crash if using jython 2.7.4 with run.py:

```
Burp.console = console = JLineConsole()
        console.set('Burp', Burp)
```

Errors are below:

```
Traceback (most recent call last):
  File "run.py", line 118, in <module>
    start_burp(opt, *args)
  File "run.py", line 65, in start_burp
    Burp.console = console = JLineConsole()
TypeError: org.python.util.JLineConsole(): expected 1 args; got 0
...
Traceback (most recent call last):
  File "run.py", line 118, in <module>
    start_burp(opt, *args)
  File "run.py", line 66, in start_burp
    console.set('Burp', Burp)
AttributeError: 'org.python.util.JLineConsole' object has no attribute 'set'
```
